# Generated by Django 3.2 on 2021-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employees_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phn',
            field=models.TextField(),
        ),
    ]
